################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.o chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.su chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.c chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F407G_DISC1 -DSTM32F4 -DSTM32F407VGTx -DARM_MATH_CM4 -DSTM32F407xx -c -I../Inc -I"D:/PROJECTS/Git/MUSCULAR-ACTIVITY-MONITORING-SYSTEM_STM32F4/STM32F407/MAIN/chip_headers/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/PROJECTS/Git/MUSCULAR-ACTIVITY-MONITORING-SYSTEM_STM32F4/STM32F407/MAIN/chip_headers/Drivers/CMSIS/Include" -I"D:/PROJECTS/Git/MUSCULAR-ACTIVITY-MONITORING-SYSTEM_STM32F4/STM32F407/MAIN/chip_headers/Drivers/CMSIS/DSP/Include" -I"D:/PROJECTS/Git/MUSCULAR-ACTIVITY-MONITORING-SYSTEM_STM32F4/STM32F407/MAIN/chip_headers/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-chip_headers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-chip_headers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo
	-$(RM) ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su
	-$(RM) ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo
	-$(RM) ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d
	-$(RM) ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./chip_headers/Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-chip_headers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

